/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author juan
 */
public class Sistema extends javax.swing.JDialog {

    /**
     * Creates new form Sistema
     */
    Clases.Sistema sis = null;

    public Sistema(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);

        sis = new Clases.Sistema();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSistema = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema");

        btnSistema.setText("Copia de Seguridad y Restauracion");
        btnSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistemaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(btnSistema)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btnSistema)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistemaActionPerformed
        // TODO add your handling code here:

        String[] options = {"Copia de Seguridad", "Restaurar"};
        int backup = JOptionPane.showOptionDialog(null, "Seleccione una opcion", "Titulo", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);

        Runtime back = Runtime.getRuntime();
        Runtime abrirres = Runtime.getRuntime();
        Runtime res = Runtime.getRuntime();

        if (backup == 0) {

            try {
                int confirmarres = JOptionPane.showConfirmDialog(null, "¿Desea crear el backup?");
                if (confirmarres == 0) {
                    back.exec("cmd.exe /K start backup.bat");
                    JOptionPane.showMessageDialog(null, "¿Backup ha sido generado en la carpeta c:/POSTGRESQL/Backup/, caso contrario vuelva a intentarlo correctamente.");
                } else {
                    JOptionPane.showMessageDialog(null, "Se cancelo backup");
                }
            } catch (Exception e) {
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "Hubo un error al generar el Backup");
            }

        } else {
            int restaurar = JOptionPane.showConfirmDialog(null, "Para restaurar se necesita eliminar las tablas de la base de datos ¿Ya tiene su copia de seguridad");
            if (restaurar == 0) {
                try {
                    sis.eliminar_tablas();
                    JOptionPane.showMessageDialog(null, "Copee el backup en esta carpeta, con el nombre \"backup\"");
                    abrirres.exec("cmd.exe /K start abrirrestore.bat");
                    int confirmarres = JOptionPane.showConfirmDialog(null, "Puso el archivo en la carpeta?");
                    if (confirmarres == 0) {
                        res.exec("cmd.exe /K start restore.bat");
                        Thread.sleep(3000);

                        /*
                        if(sis.existe_tablas()){
                          JOptionPane.showMessageDialog(null,"Las tablas han sido restauradas");
                        }else{
                          JOptionPane.showMessageDialog(null,"Error las tablas no fueron restauradas");
                        }
                         */
                        JOptionPane.showMessageDialog(null, "Las tablas han sido restauradas, caso contrario, vuelva a intentarlo nuevamente correctamente.");
                    } else {
                        JOptionPane.showMessageDialog(null, "Vuelva a intertarlo");
                    }
                } catch (Exception e) {
                    System.out.println(e);
                    JOptionPane.showMessageDialog(null, "Hubo un error al generar al restaurar");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Genere el backup primero");
            }
        }


    }//GEN-LAST:event_btnSistemaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Sistema dialog = new Sistema(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSistema;
    // End of variables declaration//GEN-END:variables
}
